version: "3"
services:
    node-app:
        build: .
        ports:
            - "3000:3000"
        environment: 
            - PORT=3000
    database:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=chetan
            - MONGO_INITDB_ROOT_PASSWORD=chetan
        volumes:
            - mongo-db:/data/db

volumes:
    mongo-db: